dbt_ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: admin
      password: adminpassword
      port: 5433
      dbname: ecommerce_db
      schema: public
      threads: 4