dbt_ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      pass: "{{ env_var('DBT_PASSWORD', '') }}"
      port: 5433
      dbname: "{{ env_var('DBT_DBNAME', 'postgres') }}"
      schema: public
      threads: 4