name: dbt CI Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_dbt_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-postgres adapter
        run: pip install dbt-postgres

      - name: Run dbt deps (Install packages)
        run: dbt deps

      - name: Run dbt parse (Validate syntax, schemas & DAG references)
        run: dbt parse
        env:
          DBT_PROFILES_DIR: .