name: dbt CI Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_dbt_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-postgres adapter
        run: pip install dbt-postgres

      - name: Create CI profiles.yml
        run: |
          cat <<EOF > profiles.yml
          dbt_ecommerce:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                user: ci_user
                password: ci_password
                port: 5432
                dbname: ci_db
                schema: public
                threads: 1
          EOF

      - name: Run dbt deps (Install packages)
        run: dbt deps
        env:
          DBT_PROFILES_DIR: .

      - name: Run dbt parse (Validate syntax, schemas & DAG references)
        run: dbt parse
        env:
          DBT_PROFILES_DIR: .